server:
  port: 8083
logging:
  level:
    root: INFO
    DriverMapper: TRACE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&useSSL=false&useUnicode=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai
    username: sy
    password: shenyue
    hikari:
      type: com.zaxxer.hikari.HikariDataSource
      minimum-idle: 1
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 1000
mybatis-plus:
  mapper-locations:
    - mapper/*